# Generated by Django 5.2.7 on 2025-10-19 06:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Area', models.CharField(max_length=50)),
                ('District', models.CharField(max_length=50)),
                ('Place', models.CharField(max_length=50)),
                ('Pin', models.CharField(max_length=10)),
                ('Post', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(max_length=50)),
                ('Type', models.CharField(max_length=50)),
                ('Price', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Message', models.CharField(max_length=1000)),
                ('FROMUSER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fromid', to=settings.AUTH_USER_MODEL)),
                ('TOUSER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toid', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pickup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Logo', models.CharField(max_length=800)),
                ('Email', models.CharField(max_length=40)),
                ('Phone', models.CharField(max_length=10)),
                ('Tagline', models.CharField(max_length=50)),
                ('Status', models.CharField(max_length=50)),
                ('AREA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.area')),
                ('AUTHUSER', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subarea', models.CharField(max_length=50)),
                ('AREA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.area')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Photo', models.CharField(max_length=800)),
                ('License', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=50)),
                ('Number', models.CharField(max_length=10)),
                ('DOB', models.DateField()),
                ('Gender', models.CharField(max_length=10)),
                ('AUTHUSER', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('SUBAREA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.subarea')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Photo', models.CharField(max_length=800)),
                ('Email', models.CharField(max_length=50)),
                ('Number', models.CharField(max_length=10)),
                ('DOB', models.DateField()),
                ('AREA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.area')),
                ('AUTHUSER', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Feedback', models.CharField(max_length=1000)),
                ('Rating', models.CharField(max_length=400)),
                ('Staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.staff')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.users')),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Complaint', models.CharField(max_length=1000)),
                ('Reply', models.CharField(max_length=1000)),
                ('Status', models.CharField(max_length=20)),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.users')),
            ],
        ),
        migrations.CreateModel(
            name='WasteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Status', models.CharField(max_length=80)),
                ('PICKUP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.pickup')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.users')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Status', models.CharField(max_length=20)),
                ('Type', models.CharField(max_length=10)),
                ('WASTEREQ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.wasterequest')),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bill', models.CharField(max_length=50)),
                ('WASTEREQ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.wasterequest')),
            ],
        ),
        migrations.CreateModel(
            name='AssignStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Status', models.CharField(max_length=20)),
                ('STAFF', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.staff')),
                ('WASTEREQ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.wasterequest')),
            ],
        ),
    ]
