# Generated by Django 5.2.7 on 2025-11-15 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='Gender',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
