# Generated by Django 5.2.7 on 2025-11-29 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_users_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='subarea',
            name='PICKUP',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='myapp.pickup'),
        ),
    ]
