# Generated by Django 5.2.7 on 2025-12-30 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_payment_type_payment_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='USER',
            new_name='USERS',
        ),
    ]
