# Generated by Django 5.2.7 on 2025-12-30 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_user_complaint_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='USER',
            new_name='USERS',
        ),
    ]
