# Generated by Django 5.2.7 on 2025-12-30 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_rename_user_feedback_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='Staff',
            new_name='STAFF',
        ),
    ]
