# Generated by Django 5.2.7 on 2025-12-30 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_rename_staff_feedback_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wasterequest',
            old_name='USER',
            new_name='USERS',
        ),
    ]
