# Generated by Django 5.2.7 on 2025-12-31 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_rename_user_wasterequest_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickup',
            name='Latitude',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pickup',
            name='Longitude',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wasterequest',
            name='Latitude',
            field=models.CharField(default='', max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wasterequest',
            name='Longitude',
            field=models.CharField(default='', max_length=80),
            preserve_default=False,
        ),
    ]
